### ISSUE TITLE
TileLink Mask

### ISSUE THREAD

**Issue by vmurali** [sifive/ProcKami#297]
```
64: 000 -> 1111_1111 = FF
32: 000 -> 0000_1111 = F
32: 100 -> 1111_0000 = F0
16: 000 -> 0000_0011 = 3
16: 010 -> 0000_1100 = C
16: 100 -> 0011_0000 = 30
16: 110 -> 1100_0000 = C0
 8: 000 -> 0000_0001 = 1
 8: 001 -> 0000_0010 = 2
 8: 010 -> 0000_0100 = 4
 8: 011 -> 0000_1000 = 8
 8: 100 -> 0001_0000 = 10
 8: 101 -> 0010_0000 = 20
 8: 110 -> 0100_0000 = 40
 8: 111 -> 1000_0000 = 80
```

**Comment by llee454** [comment]
[ where | size ]

**Comment by llee454** [comment]
- [ ] Compute the mask function on the examples given above.

**Comment by llee454** [comment]
https://github.com/sifive/ProcKami/pull/300

**Comment by llee454** [comment]
- [ ] Move mask and shift functions to MemOpsFuncs.v
- [ ] Merge tests and refactored mask and shift functions with current master.

**Comment by llee454** [comment]
- [ ] revise shiftAmt in TlUH.v so that it accepts a PAddr rather than a nat.
- [ ] revise the tests for shiftAmt so that the upper bits of the PAddr are random while the lower 3 bits cover all of the cases illustrated in the table above.
- [ ] convert the compute statements in the tests for shiftAmt and mask to Goal statements.
- [ ] add hex equivalents to the table given above in this Issue.

**Comment by llee454** [comment]
https://github.com/sifive/ProcKami/pull/301

**Comment by llee454** [comment]
https://github.com/sifive/ProcKami/pull/301
